name: Publish Pre-Release
on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-*'
env:
  PRIVATE_REGISTRY_URL: https://npm.pkg.github.com
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Dependencies
        uses: ./.github/actions/setup-dependencies
        with:
          registry-url: ${{ env.PRIVATE_REGISTRY_URL }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GHP_TOKEN }}
      - name: Build
        run: npm run build
        with:
          build-artifacts-name: dist
  Prepare-Pre-Release:
    name: Prepare Pre-Release
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Dependencies
        uses: ./.github/actions/setup-dependencies
        with:
          registry-url: ${{ env.PRIVATE_REGISTRY_URL }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GHP_TOKEN }}
      - name: Fetch Build Artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Upload Tarball To Pre-Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: '${{ secrets.GHP_TOKEN }}'
          file_glob: true
          file: |
            dist/*.pgmmv.zip
          tag: '${{ github.ref }}'
          prerelease: true
